import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import GlobalProvider from "@/components/organisms/GlobalProvider";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vintagee | Beli dan jual pakaianmu disini",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  hideLayout?: boolean;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtree.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
